project:
  type: website

website:
  title: "StepuP meetings"
  # cookie-consent: true
  navbar:
    background: primary
    pinned: true
    left:
      - text: Zurich 2024
        href: zurich2024.qmd
      - text: Amsterdam 2024
        href: amsterdam2024.qmd

  page-footer: 
    left: "Copyright 2024, Julius Welzel" 


format:
  html:
    theme: zephyr
    css: styles.css
    toc: true